[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[dev]
  command = "npm start"
  functions = "functions" 
  publish = "dist"
  port=8000 # destination port to use in browser. Lambda dev server is started on same port
  targetPort=3000 # port that local rollup server is running on

[[headers]]
  for = "/"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, DELETE, PUT"
    "Can't-Be-Evil" = "true"
    Cache-Control = "no-store, no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, DELETE, PUT"
    "Can't-Be-Evil" = "true"
    Cache-Control = "no-store, no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, DELETE, PUT"
    "Can't-Be-Evil" = "true"
    Cache-Control = "no-store, no-cache"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
